import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="min-h-screen"
      >
        <div 
            className=" flex items-center justify-between"
            style={{padding: "0 1rem"}}
        >
            <h1 className="text-amber-50">ReadFree</h1>

            <div 
                className="flex md:flex-row flex-col justify-between"
                style={{marginTop: "15px", gap: "2rem"}}    
            >
                
                    <button 
                        className="bg-blue-200 rounded-3xl text text-[#121212] font-bold cursor-pointer"
                        style={{padding: "0.8rem"}}
                    >
                        Login/Registro
                    </button>

        
                    <button 
                        className="bg-blue-200 rounded-3xl text-[#121212] font-bold cursor-pointer"
                        style={{padding: "0.8rem"}}
                    >
                        Favoritos
                    </button>
                
            </div>
        </div>
        {children}
      </body>
    </html>
  );
}
